# syntax=docker/dockerfile:1

ARG NODE_VERSION=24.12.0-alpine

FROM node:${NODE_VERSION}
WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 4200
CMD ["npm", "start", "--", "--host=0.0.0.0", "--poll=2000"]
