# syntax=docker/dockerfile:1

ARG NODE_VERSION=24.12.0-alpine

FROM node:${NODE_VERSION}
WORKDIR /app

ENV NODE_ENV=development

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,target=/root/.local/share/pnpm/store pnpm install --frozen-lockfile

COPY . .

EXPOSE 4200
CMD ["pnpm", "start", "--", "--host=0.0.0.0", "--poll=2000"]
