import { PortfolioMedia } from './video.model';

export const PORTFOLIO_MEDIA: readonly PortfolioMedia[] = [
  {
    id: 'ctc-clinic-overview',
    mediaType: 'video',
    title: 'Circulating Tumour Cells in Clinical Decision-Making',
    summary:
      'Conference presentation on how CTC molecular analysis from microfluidic devices supports treatment monitoring in gastrointestinal cancer.',
    language: 'EN',
    topic: 'circulating-tumour-cells',
    audience: 'clinicians',
    platform: 'youtube',
    embedId: 'dQw4w9WgXcQ',
    publishedAt: '2024-02-08',
    durationMinutes: 19,
    tags: ['ctc', 'precision-oncology', 'clinical-translation', 'microfluidics'],
  },
  {
    id: 'microfluidics-device-development',
    mediaType: 'video',
    title: 'Microfluidic Device Development: From Prototype to Clinical Validation',
    summary:
      'Walkthrough of the end-to-end R&D cycle for a microfluidic CTC capture platform, covering technical optimization, fabrication, and proof-of-concept with patient samples at IPO-Porto.',
    language: 'EN',
    topic: 'microfluidics',
    audience: 'researchers',
    platform: 'vimeo',
    embedId: '76979871',
    publishedAt: '2023-11-21',
    durationMinutes: 16,
    tags: ['microfluidics', 'liquid-biopsy', 'device-development', 'INL'],
  },
  {
    id: 'gi-cancer-clonal-evolution',
    mediaType: 'video',
    title: 'Clonal Evolution and Immune Escape in GI Cancer',
    summary:
      'Research seminar presenting PhD findings on molecular heterogeneity in circulating tumour cells and their implications for immune escape in gastrointestinal cancer.',
    language: 'EN',
    topic: 'gastrointestinal-oncology',
    audience: 'researchers',
    platform: 'youtube',
    embedId: '3JZ_D3ELwOQ',
    publishedAt: '2024-05-04',
    durationMinutes: 22,
    tags: ['clonal-evolution', 'immune-escape', 'gastrointestinal-cancer', 'PhD-research'],
  },
  {
    id: 'pint-of-science-talk',
    mediaType: 'video',
    title: 'Tiny Cells, Big Stories: Cancer Science for Everyone',
    originalTitle: 'Células Pequenas, Histórias Gigantes',
    summary:
      'Pint of Science festival talk translating oncology and nanotechnology concepts into accessible language for a general audience in Guimarães.',
    language: 'PT',
    topic: 'science-outreach',
    audience: 'general-public',
    platform: 'youtube',
    embedId: 'L_jWHffIx5E',
    publishedAt: '2023-06-01',
    durationMinutes: 15,
    tags: ['pint-of-science', 'portuguese', 'public-engagement', 'nanotechnology'],
  },
  {
    id: 'clinical-research-gcp',
    mediaType: 'video',
    title: 'Good Clinical Practice in Translational Oncology Research',
    summary:
      'Presentation on applying ICH GCP principles to translational research workflows, bridging regulatory compliance with clinical sample management in oncology studies.',
    language: 'EN',
    topic: 'clinical-evidence',
    audience: 'clinicians',
    platform: 'vimeo',
    embedId: '22439234',
    publishedAt: '2024-09-14',
    durationMinutes: 14,
    tags: ['GCP', 'clinical-research', 'regulatory', 'translational-oncology'],
  },
  {
    id: 'ctc-microfluidics-illustration',
    mediaType: 'illustration',
    title: 'CTC Capture: Microfluidic Device Workflow',
    summary:
      'Scientific illustration showing the microfluidic device workflow from blood sample processing to single-cell molecular analysis of circulating tumour cells.',
    language: 'EN',
    topic: 'microfluidics',
    audience: 'clinicians',
    imagePath: '/assets/illustrations/ctc-translation-map.svg',
    altText:
      'Scientific illustration depicting a microfluidic chip capturing circulating tumour cells from a blood sample, with downstream molecular analysis steps.',
    credit: 'Adobe Illustrator · Self-produced',
    publishedAt: '2024-10-01',
    tags: ['illustration', 'ctc', 'microfluidics', 'liquid-biopsy'],
  },
  {
    id: 'science-outreach-schools-poster',
    mediaType: 'illustration',
    title: 'Nanotechnology for Kids: Visual Storyboard',
    summary:
      'Illustrated storyboard designed for interactive sessions in schools, simplifying nanotechnology and cancer biology concepts with age-appropriate metaphors.',
    language: 'PT',
    topic: 'science-outreach',
    audience: 'children',
    imagePath: '/assets/illustrations/children-science-storyboard.svg',
    altText:
      'Colorful storyboard with simple icon-based steps explaining nanotechnology concepts for children in Portuguese school outreach sessions.',
    credit: 'Workshop teaching material · Adobe Illustrator',
    publishedAt: '2024-03-18',
    tags: ['illustration', 'children', 'portuguese', 'outreach', 'nanotechnology'],
  },
  {
    id: 'muwell-3d-cancer-models',
    mediaType: 'illustration',
    title: 'µWell Platform for 3D Cancer Models',
    summary:
      'Visual overview of the µWell platform developed during PhD research for growing 3D cancer models, showing the workflow from cell seeding to tumour spheroid analysis.',
    language: 'EN',
    topic: 'circulating-tumour-cells',
    audience: 'researchers',
    imagePath: '/assets/illustrations/evidence-brief-template.svg',
    altText:
      'Diagram showing µWell microfluidic platform steps: cell seeding, 3D spheroid growth, and downstream analysis for cancer research.',
    credit: 'PhD research material · Adobe Illustrator',
    publishedAt: '2024-07-12',
    tags: ['illustration', 'µWell', '3D-models', 'cancer-research', 'microfluidics'],
  },
];
